---
# Available languages: eng (English) and vie (Vietnamese).
language: "eng"

# debugMode: false > No logs will be logged.
debugMode: true

# logFile: "single" > All logs will be logged in a single file.
# logFile: "separate" > Events logs will be logged in a separate files.
logFile: "single"

# The default configuration will be used if this field is modified.
configVersion: "0.0.1"
...
